### PR TITLE
Header, navbar and footer integrated, now fully responsive

### PR DESCRIPTION
**Pull request by angelbaezsa**

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for sending your project for review, it already looks decent! I marked several small issues and hope that they can help you to improve your project and get more points. Good luck!✨

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Text in modal submit button and switch link should be different in different modal windows - please check the mockup
    * Preloader and not found components looks differently from the mockup
    * Pointer cursor should be used only for internactive items, not for the page itself
    * Mismatches with the main page on 1440px (please ignore the content differences in footer) https://pasteboard.co/CAgZaKrizIGl.png
    * Mismatches with the main page on 768px https://pasteboard.co/ONXyBJ5puG60.png https://pasteboard.co/C3RY3k0Qk3EN.png https://pasteboard.co/UJZ3oPF7I5FJ.png
    * Mismatches with the main page on 320px https://pasteboard.co/vQhcXS2gYeq2.png https://pasteboard.co/HaBAHKcvjU6p.png https://pasteboard.co/PzkAjWv1RzAU.png https://pasteboard.co/pzmexj5JphU4.png
    * Incorrect background color of the mobile nav menu
    * modal window shouldn't have bottom free space on mobile screen resolutions
    * Mismatches with the saved-news page on 1440px https://pasteboard.co/k5iCBtevHLzS.png, 768px https://pasteboard.co/w7GoAXLKwzxe.png
    * logo should be visible on mobile nav menu on saved-news page
    * Not all necessary fonts are used in the project, please import them and use in the project according to the mockup
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All project components should be centered horizontally on intermediate screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * Signin button in mobile nav menu doesn't work
- [ ]  Classes are named according to BEM specifications.
    * modifiers shouldn't be used without their base classes, for example navbar_black can't be used without `navbar` class etc. Please fix all similar cases **throughout the project**
    * BEM elements can't be used outside their BEM blocks, for example you can't used `navbar__logo` outside the `nav` block. Please fix all similar cases **throughout the project**
    * `toggle-menu_item` should be a BEM element
    * Please don't use capital letters and spaces in class names
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * You should use `header`, `main` and `sections` tags in your project where necessary
    * `form__url` should be a link
    * `saved-news` page doesn't have `h1` title
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * Project has several eslint warnings

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Cards save/trash button should have clicked state
    * All interacive items (links/buttons) should have pointer cursor
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
    * `form__url` should be highlighted when focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * All `font-family` styles should have more than only primary font as value
- [ ]  Images have an `alt` attribute containing appropriate values.
    * `alt` attributes shouldn't be empty **throughout the project**
- [x]  Raster and vector images have been optimized.

## Number of points: 42

**Comment by FiLLa-FaS** [comment]
# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Mismatches with the main page on 768px https://pasteboard.co/r4hOtjc8G4SC.png
    * Mismatches with the main page on 320px https://pasteboard.co/M9beieScbtt6.png https://pasteboard.co/pSYh0lDfUS2S.png
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All project components should be centered horizontally on intermediate screen resolutions (check the `about me` section)
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * modifiers shouldn't be used without their base classes, for example `navbar_black` can't be used without `navbar` class etc. Please fix all similar cases **throughout the project**
    * BEM elements can't be used outside their BEM blocks, for example you can't used `navbar__logo` outside the `nav` block. Please fix all similar cases **throughout the project**
    * Please don't use capital letters and spaces in class names
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * You should use sections tags in your project where necessary
    * `form__url` should be a link
    * `saved-news` page doesn't have h1 title
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * Project has several eslint warnings

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Cards save/trash button should have clicked state
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `form__url` should be highlighted when focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
    * `alt` attributes shouldn't be empty **throughout the project**
- [x]  Raster and vector images have been optimized.

## Number of points: 56

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for the corrections, your project looks much better! Several small issues below are left. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Mismatches with the main page on 320px https://pasteboard.co/usARUGMqNLly.png
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All project components should be centered horizontally on intermediate screen resolutions (check the about me section on 1001px+)
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * modifiers shouldn't be used without their base classes, for example `main__show-more_button` can't be used without `main__show-more` class etc. Please fix all similar cases **throughout the project**
    * BEM elements can't be used outside their BEM blocks, for example you can't used `navbar__saved-news` outside the `navbar` block. Please fix all similar cases throughout the project
    * Please don't use capital letters and spaces in class names
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * Project has several eslint warnings

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `form__url` should be visually highlighted when focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [ ]  Images have an `alt` attribute containing appropriate values.
    * `icon-github` alt attribute shouldn't be empty
- [x]  Raster and vector images have been optimized.

## Number of points: 62

**Comment by FiLLa-FaS** [comment]
Hi! Several small issues below are left:⏬. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Mismatches with the main page on 320px https://pasteboard.co/82ff3LBEWakc.png
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * Please don't use capital letters and spaces in class names
    * BEM elements can't be used outside their BEM blocks, for example you can't used `cardlist__card-container` outside the `cardlist` block. Please fix all similar cases **throughout the project**
    * modifiers shouldn't be used without their base classes, for example `cardlist__show-more_button` can't be used without `cardlist__show-more` class etc. Please fix all similar cases throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * The project has eslint warnings and errors

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `form__url` should be visually highlighted when focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 77

**Comment by angelbaezsa** [comment]
Form elements should be highlighted when focused.
form__url should be visually highlighted when focused

Hi, thanks for the review.
When you say that you want the form__url highlighted I am not quite sure what you mean. 
I had pseudo classes :hover :active but when I apply the :focus pseudo class nothing happens. 
What is the best approach to proceed? 

Although the capital letter in the classes aren't coming up and they seem normal on the version that I am working on. 
I checked with a regex className="[A-Z][^"]*" manually and nothing matches.

**Comment by FiLLa-FaS** [comment]
Hi! You can easily check the focus state by opening the modal window and pressing the `tab` key several times - link should be highlighted somehow. And you have capital letters and space in `modal` modifiers - please check the second class of `modal` block.

**Comment by FiLLa-FaS** [comment]
Hi! You've got more than 80 points, so I'm really glad to accept your project! Good luck on the next stage 🙌🚀

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * BEM elements can't be used outside their BEM blocks, for example you can't used `cardlist__card-container` outside the `cardlist` block. Please fix all similar cases **throughout the project**
    * modifiers shouldn't be used without their base classes, for example `cardlist__show-more_button` can't be used without `cardlist__show-more` class etc. Please fix all similar cases **throughout the project**
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * The project has eslint warnings

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 92

**Pull request merged**
